import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import MidNav from "@/components/shared/MidNav";
import BottomNav from "@/components/shared/BottomNav";
import AuthProvider from "@/providers/AuthProvider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
export const metadata = {
  title: "PORTO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-50`}>
        <AuthProvider>
          <div className="bg-blue-500">
            <div className="max-w-5xl mx-auto ">
              <Header />
              <MidNav />
            </div>
          </div>
          <BottomNav />
          {children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
